"""
schema.py — Frozen candidate schema (Section 2.1 of the sprint plan).

This is the single source of truth for what extract_candidate() must return.
Every LLM response is validated against this model before it leaves the
module. Pydantic's default-filling behavior is what powers the "repair pass"
described in the sprint plan: any missing/invalid field falls back to a safe
default instead of raising and crashing the pipeline.

NOTE: This mirrors shared-contracts/schema.json. If that file changes,
update this model in the same commit and post in the team channel
(per README Section 7 — frozen contracts don't change silently).
"""
from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, field_validator, model_validator

from text_utils import sanitize_candidate_strings, titlecase_name


class Skill(BaseModel):
    """A single skill with its associated tools.

    LLMs default to flattening this into a plain string list if not
    explicitly instructed otherwise (see prompt.py's few-shot example) —
    this model is what catches it if that happens anyway.
    """
    skill: str = ""
    tools: List[str] = Field(default_factory=list)

    @field_validator("tools", mode="before")
    @classmethod
    def _coerce_tools_to_list(cls, v):
        # Defensive: if the LLM returns a single string instead of a list,
        # wrap it rather than failing validation outright.
        if v is None:
            return []
        if isinstance(v, str):
            return [v] if v.strip() else []
        return v


class Experience(BaseModel):
    company: str = ""
    position: str = ""
    start_date: str = ""  # "YYYY-MM" or "Present" (Present shouldn't appear here in practice)
    end_date: str = ""    # "YYYY-MM" or "Present"
    description: str = ""


class Education(BaseModel):
    institution: str = ""
    degree: str = ""
    field: str = ""
    year: str = ""


class CandidateExtraction(BaseModel):
    """The exact shape extract_candidate() returns as a dict."""

    # Not generated by this module — Member 3's backend assigns this.
    # Always None/omitted from our side (Section 2.1).
    candidate_id: Optional[str] = None

    full_name: str = ""
    email: str = ""
    phone: str = ""

    # Always returned empty — HR assigns/edits this after upload, it is
    # never inferred from the CV itself (a candidate's CV doesn't reliably
    # state which open position they're being considered for).
    applied_position: str = ""

    summary: str = ""

    skills: List[Skill] = Field(default_factory=list)
    experience: List[Experience] = Field(default_factory=list)

    # Computed programmatically in experience_calc.py, never trusted from
    # the LLM's own arithmetic (Section 2.1 / 3).
    experience_total: float = 0.0

    # Numbers; default to 0 when the CV is silent on pay — never hallucinated.
    current_salary: float = 0.0
    expected_salary: float = 0.0

    education: List[Education] = Field(default_factory=list)

    # HR-entered post-upload fields. Never extracted or generated here.
    hr_comment: str = ""
    line_manager_comment: str = ""

    extraction_confidence: float = 0.5
    raw_text_snippet: str = ""

    @model_validator(mode="before")
    @classmethod
    def _sanitize_incoming_strings(cls, data):
        """Runs before any field-level validation. Strips mojibake and the
        Unicode replacement character ('\ufffd') out of EVERY string in the
        payload — including nested skills/experience/education entries, not
        just top-level fields. This is the single fix point for garbled
        characters, regardless of whether they came from a PDF with a
        broken font encoding or an LLM echoing back garbled input text."""
        if isinstance(data, dict):
            return sanitize_candidate_strings(data)
        return data

    @field_validator("full_name", mode="after")
    @classmethod
    def _titlecase_full_name(cls, v: str) -> str:
        # Normalizes name casing regardless of how the LLM formatted it
        # ("JOHN SMITH", "john smith", "JOHN smith"), while respecting
        # surname particles ("van", "de", "bin"...), apostrophes, and
        # hyphens (see text_utils.titlecase_name). Still trivially
        # inline-editable by HR afterward if it ever needs a manual fix.
        return titlecase_name(v) if v else v

    @field_validator("current_salary", "expected_salary", "experience_total", mode="before")
    @classmethod
    def _coerce_numeric_defaults(cls, v):
        # LLMs sometimes emit "" , null, "N/A", or "unknown" for numeric
        # fields the CV doesn't mention. Treat all of that as 0 rather
        # than letting validation fail and triggering a full fallback.
        if v is None:
            return 0.0
        if isinstance(v, str):
            stripped = v.strip().replace(",", "")
            if stripped == "" or not _looks_numeric(stripped):
                return 0.0
            try:
                return float(stripped)
            except ValueError:
                return 0.0
        return v

    @field_validator("extraction_confidence", mode="before")
    @classmethod
    def _clamp_confidence(cls, v):
        try:
            f = float(v)
        except (TypeError, ValueError):
            return 0.5
        return max(0.0, min(1.0, f))

    def to_output_dict(self) -> dict:
        """Serialize in the exact key order/shape of the frozen schema."""
        data = self.model_dump()
        return data


def _looks_numeric(s: str) -> bool:
    try:
        float(s)
        return True
    except ValueError:
        return False


REQUIRED_TOP_LEVEL_KEYS = list(CandidateExtraction.model_fields.keys())
