"""Round 4: hr_accounts, comment_logs, resume_versions, status_history,
candidate_change_log + the new candidate columns.

Revision ID: 0001_round4
Revises:
Create Date: 2026-09-18

Written by hand rather than autogenerated, because the target database already
exists in everyone's working copy and autogenerate would also try to "fix" the
pre-Alembic tables. `upgrade()` is additive only: it creates the five new tables
and adds four columns to `candidates`. No existing column is dropped - the two
deprecated comment columns stay until F3 phase 2.
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_round4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "hr_accounts",
        sa.Column("account_id", sa.String(), primary_key=True),
        sa.Column("username", sa.String(), nullable=False, unique=True),
        sa.Column("email", sa.String(), nullable=False, unique=True),
        sa.Column("full_name", sa.String(), nullable=False, server_default=""),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False, server_default="hr"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_hr_accounts_username", "hr_accounts", ["username"])

    op.create_table(
        "comment_logs",
        sa.Column("comment_id", sa.String(), primary_key=True),
        sa.Column("candidate_id", sa.String(), nullable=False),
        sa.Column("author_account_id", sa.String(), nullable=False),
        sa.Column("author_name", sa.String(), nullable=False, server_default=""),
        sa.Column("author_role", sa.String(), nullable=False, server_default="hr"),
        sa.Column("comment_type", sa.String(), nullable=False, server_default="general"),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("commented_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_edited", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.candidate_id"]),
        sa.ForeignKeyConstraint(["author_account_id"], ["hr_accounts.account_id"]),
    )
    op.create_index(
        "ix_comment_logs_candidate",
        "comment_logs",
        ["candidate_id", sa.text("commented_at DESC")],
    )

    op.create_table(
        "resume_versions",
        sa.Column("version_id", sa.String(), primary_key=True),
        sa.Column("candidate_id", sa.String(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("blob_path", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uploaded_by", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.candidate_id"]),
        sa.ForeignKeyConstraint(["uploaded_by"], ["hr_accounts.account_id"]),
    )
    op.create_index("ix_resume_versions_candidate", "resume_versions", ["candidate_id"])

    op.create_table(
        "status_history",
        sa.Column("history_id", sa.String(), primary_key=True),
        sa.Column("candidate_id", sa.String(), nullable=False),
        sa.Column("from_status", sa.String(), nullable=True),
        sa.Column("to_status", sa.String(), nullable=False),
        sa.Column("changed_by", sa.String(), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False, server_default=""),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.candidate_id"]),
        sa.ForeignKeyConstraint(["changed_by"], ["hr_accounts.account_id"]),
    )
    op.create_index("ix_status_history_candidate", "status_history", ["candidate_id"])

    op.create_table(
        "candidate_change_log",
        sa.Column("change_id", sa.String(), primary_key=True),
        sa.Column("candidate_id", sa.String(), nullable=False),
        sa.Column("field", sa.String(), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=False, server_default=""),
        sa.Column("new_value", sa.Text(), nullable=False, server_default=""),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_by", sa.String(), nullable=False, server_default=""),
        sa.Column("source", sa.String(), nullable=False, server_default="manual_edit"),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.candidate_id"]),
    )
    op.create_index(
        "ix_candidate_change_log_candidate", "candidate_change_log", ["candidate_id"]
    )

    # --- new candidate columns. server_default so existing rows are not NULL;
    # the NULL RULE says the payload never contains one.
    with op.batch_alter_table("candidates") as batch:
        batch.add_column(sa.Column("email_normalized", sa.String(), nullable=True))
        batch.add_column(sa.Column(
            "before_rejected_status", sa.String(), nullable=False, server_default=""
        ))
        batch.add_column(sa.Column(
            "possible_duplicate_of", sa.JSON(), nullable=False, server_default="[]"
        ))
    op.create_index("ix_candidates_email_normalized", "candidates", ["email_normalized"])

    # Backfill the duplicate key for rows that already exist. NULLIF keeps blank
    # emails as NULL so a UNIQUE index can be added later without every
    # email-less candidate colliding with every other one.
    op.execute(
        "UPDATE candidates "
        "SET email_normalized = NULLIF(LOWER(TRIM(email)), '') "
        "WHERE email_normalized IS NULL"
    )
    # NOTE: the UNIQUE index on email_normalized is deliberately NOT created
    # here. Before F4 the API created a second candidate on every re-upload, so
    # existing databases can already hold duplicate emails - a UNIQUE index
    # would fail to build, or turn a later PUT into a 500. Add it in a follow-up
    # migration once the duplicates HR sees in `possible_duplicate_of` have been
    # merged.


def downgrade() -> None:
    op.drop_index("ix_candidates_email_normalized", table_name="candidates")
    with op.batch_alter_table("candidates") as batch:
        batch.drop_column("possible_duplicate_of")
        batch.drop_column("before_rejected_status")
        batch.drop_column("email_normalized")

    op.drop_index("ix_candidate_change_log_candidate", table_name="candidate_change_log")
    op.drop_table("candidate_change_log")
    op.drop_index("ix_status_history_candidate", table_name="status_history")
    op.drop_table("status_history")
    op.drop_index("ix_resume_versions_candidate", table_name="resume_versions")
    op.drop_table("resume_versions")
    op.drop_index("ix_comment_logs_candidate", table_name="comment_logs")
    op.drop_table("comment_logs")
    op.drop_index("ix_hr_accounts_username", table_name="hr_accounts")
    op.drop_table("hr_accounts")
